#!/usr/bin/env python3
"""
创建 GitHub Release 用于发布 .so 文件

将编译后的 .so 文件打包为 GitHub Release 附件。

使用方法:
    1. 设置 GitHub Token: export GITHUB_TOKEN=your_token
    2. 运行脚本: python scripts/utils/create_release.py

作者: jetson-mamba-ssm 项目
日期: 2026-02-02
"""

import os
import sys
import subprocess
import requests
from pathlib import Path
from datetime import datetime
import tarfile
import tempfile

# 颜色输出
GREEN = "\033[92m"
RED = "\033[91m"
YELLOW = "\033[93m"
BLUE = "\033[94m"
CYAN = "\033[96m"
RESET = "\033[0m"


def print_header(msg):
    print(f"\n{CYAN}{'=' * 60}{RESET}")
    print(f"{BLUE}{msg}{RESET}")
    print(f"{CYAN}{'=' * 60}{RESET}\n")


def print_info(msg):
    print(f"{BLUE}[INFO]{RESET} {msg}")


def print_success(msg):
    print(f"{GREEN}[✓]{RESET} {msg}")


def print_error(msg):
    print(f"{RED}[✗]{RESET} {msg}")


def print_warning(msg):
    print(f"{YELLOW}[!]{RESET} {msg}")


def create_so_archive(project_root):
    """创建 .so 文件压缩包"""
    print_header("创建 .so 文件压缩包")

    site_packages = Path("/home/jetson/.local/lib/python3.10/site-packages")

    # 查找 .so 文件
    so_files = []

    # causal_conv1d CUDA 扩展
    for so_file in site_packages.glob("*causal_conv1d*.so"):
        if 'aarch64' in so_file.name:
            so_files.append(so_file)

    # selective_scan CUDA 扩展
    for so_file in site_packages.glob("*selective_scan*.so"):
        if 'aarch64' in so_file.name:
            so_files.append(so_file)

    if not so_files:
        print_error("未找到 ARM64 .so 文件")
        return None

    # 创建压缩包
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    archive_name = f"mamba_ssm_so_files_{timestamp}.tar.gz"

    # 保存到 backup 目录
    backup_dir = project_root / "backup"
    backup_dir.mkdir(exist_ok=True)
    archive_path = backup_dir / archive_name

    print_info(f"创建压缩包: {archive_name}")

    with tempfile.TemporaryDirectory() as temp_dir:
        temp_path = Path(temp_dir) / "so_files"
        temp_path.mkdir()

        # 复制文件
        total_size = 0
        for so_file in so_files:
            dst = temp_path / so_file.name
            shutil_copy2(so_file, dst)
            total_size += so_file.stat().st_size
            size_mb = so_file.stat().st_size / (1024**2)
            print_success(f"  {so_file.name} ({size_mb:.1f} MB)")

        # 创建 README
        readme_content = f"""# Mamba-SSM CUDA Extension .so Files

## 编译信息

- 备份时间: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
- JetPack 版本: R36 (release), REVISION: 4.7
- Python 版本: 3.10.12
- CUDA 版本: 12.6
- TensorRT 版本: 10.7.0

## 文件列表

"""

        for so_file in so_files:
            size_mb = so_file.stat().st_size / (1024**2)
            readme_content += f"- `{so_file.name}` ({size_mb:.1f} MB)\n"

        readme_content += f"""
## 总大小

{total_size / (1024**2):.1f} MB (压缩前)

## 解压方法

```bash
# 解压
tar -xzf {archive_name}
cd so_files

# 复制到 site-packages
sudo cp *.so /usr/local/lib/python3.10/site-packages/
# 或
cp *.so ~/pythonProject/lib/python3.10/site-packages/
```

## 系统要求

- NVIDIA Jetson Orin/Xavier/Nano (ARM64/aarch64)
- Python 3.10
- CUDA 12.6
- PyTorch 2.x (JetPack 版本)

## 兼容性

| 设备 | 兼容性 |
|------|--------|
| Jetson Orin | ✅ 完全兼容 |
| Jetson Xavier | ✅ 兼容 (可能需要重新编译) |
| Jetson Nano | ⚠️  可能需要重新编译 |

## 版本对应

此 .so 文件包对应以下 wheel 版本:
- causal_conv1d-1.6.0+jetson-cp310-cp310-linux_aarch64.whl
- mamba_ssm-2.2.4+jetson-cp310-cp310-linux_aarch64.whl

## 注意事项

1. 这些 .so 文件是在特定 JetPack 版本下编译的
2. 不同 JetPack 版本可能需要重新编译
3. ARM64 架构的 .so 文件不能在 x86_64 上使用
4. 建议使用提供的 wheel 文件，已包含所有必要补丁

---

Generated by jetson-mamba-ssm project
https://github.com/snowolf-zlex/Jetson-Mamba-SSM/jetson-mamba-ssm
"""

        (temp_path / "README.md").write_text(readme_content)

        # 创建压缩包
        with tarfile.open(archive_path, "w:gz") as tar:
            tar.add(temp_path, arcname="so_files")

    archive_size = archive_path.stat().st_size / (1024**2)

    print(f"\n{CYAN}{'=' * 60}{RESET}")
    print_success(f"压缩包已创建！")
    print_info(f"文件: {archive_path}")
    print_info(f"大小: {archive_size:.1f} MB")
    print_info(f"压缩率: {archive_size / (total_size / (1024**2)) * 100:.1f}%")
    print(f"{CYAN}{'=' * 60}{RESET}\n")

    return archive_path


def shutil_copy2(src, dst):
    """替代 shutil.copy2"""
    import shutil
    return shutil.copy2(src, dst)


def create_github_release(archive_path, repo_owner, repo_name, tag, token):
    """创建 GitHub Release"""
    print_header("创建 GitHub Release")

    # 检查 token
    if not token:
        token = os.environ.get("GITHUB_TOKEN")
        if not token:
            print_error("未设置 GitHub Token")
            print_info("请设置环境变量: export GITHUB_TOKEN=your_token")
            print_info("或在 GitHub 生成 Personal Access Token:")
            print_info("  1. Settings → Developer settings → Personal access tokens → Tokens (classic)")
            print_info("  2. Generate new token (需要 repo 权限)")
            return None

    headers = {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github.v3+json"
    }

    # 检查 tag 是否已存在
    print_info(f"检查 tag: {tag}")
    response = requests.get(
        f"https://api.github.com/repos/{repo_owner}/{repo_name}/releases/tags/{tag}",
        headers=headers
    )

    if response.status_code == 200:
        print_warning(f"Tag {tag} 已存在，将创建新 release")
        release_name = f"SO Files {tag}"
        body = f"""
Mamba-SSM CUDA Extension .so 文件备份

包含编译后的 .so 文件，可用于快速部署而无需重新编译。

## 安装方法

```bash
# 下载 {archive_path.name}
# 解压并安装
tar -xzf {archive_path.name}
cd so_files
cp *.so /usr/local/lib/python3.10/site-packages/
```

## 文件信息

- 文件名: {archive_path.name}
- 大小: {archive_path.stat().st_size / (1024**2):.1f} MB
- 创建时间: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

## 对应版本

- mamba-ssm: 2.2.4+jetson
- causal-conv1d: 1.6.0+jetson
"""

        # 删除旧 release
        release_data = response.json()
        release_id = release_data["id"]

        print_info(f"删除旧 release: {release_data['name']}")
        requests.delete(
            f"https://api.github.com/repos/{repo_owner}/{repo_name}/releases/{release_id}",
            headers=headers
        )
        print_success("旧 release 已删除")

    elif response.status_code != 404:
        print_error(f"检查 tag 失败: {response.status_code}")
        return None

    # 创建新的 release
    print_info(f"创建新 release: {tag}")

    release_data = {
        "tag_name": tag,
        "name": f"Mamba-SSM SO Files {tag}",
        "body": f"""Mamba-SSM CUDA Extension .so 文件备份 ({tag})

## 内容

包含以下编译后的 .so 文件:
- causal_conv1d_cuda.cpython-310-aarch64-linux-gnu.so
- selective_scan_cuda.cpython-310-aarch64-linux-gnu.so

## 系统要求

- NVIDIA Jetson (ARM64/aarch64)
- Python 3.10
- CUDA 12.6
- JetPack R36

## 安装方法

```bash
# 下载并解压
tar -xzf {archive_path.name}
cd so_files

# 复制到 site-packages
cp *.so /usr/local/lib/python3.10/site-packages/
```

## 版本对应

- mamba-ssm: 2.2.4+jetson
- causal-conv1d: 1.6.0+jetson

## 注意事项

这些 .so 文件是在特定 JetPack 版本下编译的。
不同 JetPack 版本可能需要重新编译。

---

备份时间: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
""",
        "draft": False,
        "prerelease": False
    }

    response = requests.post(
        f"https://api.github.com/repos/{repo_owner}/{repo_name}/releases",
        headers=headers,
        json=release_data
    )

    if response.status_code != 201:
        print_error(f"创建 release 失败: {response.status_code}")
        print_error(response.text)
        return None

    release_data = response.json()
    release_id = release_data["id"]
    upload_url = release_data["upload_url"]

    print_success(f"Release 已创建: {release_data['html_url']}")

    # 上传附件
    print_info(f"上传附件: {archive_path.name}")

    with open(archive_path, "rb") as f:
        upload_response = requests.post(
            upload_url.replace("{?name,name}", f"?name={archive_path.name}"),
            headers={
                **headers,
                "Content-Type": "application/gzip"
            },
            data=f
        )

    if upload_response.status_code != 201:
        print_error(f"上传附件失败: {upload_response.status_code}")
        print_error(upload_response.text)
        return None

    print_success(f"附件已上传: {upload_response.json()['browser_url']}")

    return release_data


def main():
    """主函数"""
    import shutil
    import argparse

    parser = argparse.ArgumentParser(description="创建 GitHub Release 发布 .so 文件")
    parser.add_argument("--owner", default="jetson-mamba-ssm", help="GitHub 仓库所有者")
    parser.add_argument("--repo", default="jetson-mamba-ssm", help="GitHub 仓库名称")
    parser.add_argument("--tag", help="Release tag (默认: so-files-vYYYYMMDD)")
    parser.add_argument("--token", help="GitHub Token (或使用 GITHUB_TOKEN 环境变量)")

    args = parser.parse_args()

    print("=" * 60)
    print("Mamba-SSM .so 文件 GitHub Release 工具")
    print("=" * 60)

    # 项目根目录
    script_dir = Path(__file__).parent.parent.parent
    project_root = script_dir

    # 生成 tag
    if not args.tag:
        args.tag = f"so-files-v{datetime.now().strftime('%Y%m%d')}"

    # 1. 创建压缩包
    archive_path = create_so_archive(project_root)
    if not archive_path:
        return 1

    # 2. 创建 GitHub Release
    if not args.token:
        print_warning("未提供 GitHub Token，跳过 Release 创建")
        print_info("压缩包已创建，可手动上传到 GitHub Release")
        print_info(f"文件位置: {archive_path}")
        return 0

    release_data = create_github_release(
        archive_path,
        args.owner,
        args.repo,
        args.tag,
        args.token
    )

    if release_data:
        print(f"\n{CYAN}{'=' * 60}{RESET}")
        print_success("GitHub Release 创建成功！")
        print_info(f"Release URL: {release_data['html_url']}")
        print_info(f"下载链接: {release_data['assets'][0]['browser_url']}")
        print(f"{CYAN}{'=' * 60}{RESET}\n")

        print_info("用户下载方法:")
        print(f"  wget {release_data['assets'][0]['browser_url']}")
        print(f"  或访问: {release_data['html_url']}")
        print()

    return 0


if __name__ == "__main__":
    sys.exit(main())
