---
name: 🐛 Bug Report
description: Report a bug or issue
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: |
        Steps to reproduce the behavior:
        1. Command used '...'
        2. Error occurred '...'
      render: bash
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description: |
        Example: Jetson Orin, JetPack R36, Python 3.10, TensorRT 10.7.0
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What you expected to happen.
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
---
